vet360/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Extensions.DependencyInjection;
using vet360.Data;
using vet360.Models;
using vet360.Services;

namespace vet360.Controllers
{
    public class CitaController : Controller
    {
        private readonly ICitaService _citaService;
        private readonly IUsuarioService _usuarioService;
        private readonly IMascotaService _mascotaService;
        private readonly IServicioService _servicioService;

        public CitaController()
        {
            _citaService = Global.ServiceProvider.GetService(typeof(ICitaService)) as ICitaService;
            _usuarioService = Global.ServiceProvider.GetService(typeof(IUsuarioService)) as IUsuarioService;
            _mascotaService = Global.ServiceProvider.GetService(typeof(IMascotaService)) as IMascotaService;
            _servicioService = Global.ServiceProvider.GetService(typeof(IServicioService)) as IServicioService;
        }

        // GET: Cita
        public ActionResult Index()
        {
            var citas = _citaService.ListarTodas();
            System.Diagnostics.Debug.WriteLine("citas ---: " + citas.Count); 
            return View(citas);
        }

        // GET: Cita/Details/5
        public ActionResult Details(int id)
        {
            var cita = _citaService.ObtenerPorId(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // GET: Cita/Create
        public ActionResult Create()
        {
            CargarListasDesplegables();
            return View();
        }

        // POST: Cita/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cita cita)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _citaService.Crear(cita);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error al crear la cita: " + ex.Message);
                }
            }
            CargarListasDesplegables();
            return View(cita);
        }

        // GET: Cita/Edit/5
        public ActionResult Edit(int id)
        {
            var cita = _citaService.ObtenerPorId(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            CargarListasDesplegables();
            return View(cita);
        }

        // POST: Cita/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cita cita)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _citaService.Actualizar(cita);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error al actualizar la cita: " + ex.Message);
                }
            }
            CargarListasDesplegables();
            return View(cita);
        }

        // GET: Cita/Delete/5
        public ActionResult Delete(int id)
        {
            var cita = _citaService.ObtenerPorId(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // POST: Cita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _citaService.Cancelar(id);
            return RedirectToAction("Index");
        }

        // GET: Cita/Confirmar/5
        public ActionResult Confirmar(int id)
        {
            _citaService.Confirmar(id);
            return RedirectToAction("Index");
        }

        private void CargarListasDesplegables()
        {
            ViewBag.UsuarioId = new SelectList(_usuarioService.ListarTodos(), "Id", "Nombre");
            ViewBag.MascotaId = new SelectList(_mascotaService.ObtenerTodas(), "Id", "Nombre");
            ViewBag.ServicioId = new SelectList(_servicioService.ListarTodos(), "Id", "NombreServicioVet");
            ViewBag.VeterinarioId = new SelectList(_usuarioService.ObtenerVeterinarios(), "Id", "Nombre");
            var horarios = _citaService.ObtenerHorariosDisponibles()
            .Select(h => new
            {
                Id = h.Id,
                Fecha = h.Fecha.ToString("yyyy-MM-dd HH:mm") // O el formato que necesités
            });

            ViewBag.HorarioId = new SelectList(horarios, "Id", "Fecha");
        }

        public ActionResult Agendar()
        {
            CargarListasDesplegables();
            var usuarioActualId = Convert.ToInt32(User.Identity.Name);
            System.Diagnostics.Debug.WriteLine("veterinarios---: " + _usuarioService.ObtenerVeterinarios().Count());
           

            return View();
        }

        [HttpGet]
        public JsonResult ObtenerFechas(int veterinarioId)
        {
            var fechas = _citaService.ObtenerFechasDisponibles(veterinarioId)
                .Select(f => f.ToString("yyyy-MM-dd"));
            return Json(fechas, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObtenerHorarios(int veterinarioId, string fecha)
        {
            var horarios = _citaService.ObtenerHorariosDisponibles()
                .Select(h => new {
                    id = h.Id,
                    hora = $"{h.HoraInicio:hh\\:mm} - {h.HoraFin:hh\\:mm}"
                });
            return Json(horarios, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Agendar(Cita cita)
        {
            System.Diagnostics.Debug.WriteLine($"VeterinarioId: {cita.VeterinarioId}");
            System.Diagnostics.Debug.WriteLine($"Fecha: {cita.HorarioId}");
            System.Diagnostics.Debug.WriteLine("Agendaaa");
            CargarListasDesplegables();
            if (!ModelState.IsValid)
            {
                System.Diagnostics.Debug.WriteLine("Agendaaa error");
                // Esto imprime los errores uno por uno en la consola del servidor (Output de Visual Studio)
                foreach (var error in ModelState)
                {
                    string key = error.Key;
                    foreach (var subError in error.Value.Errors)
                    {
                        System.Diagnostics.Debug.WriteLine($"[ERROR] Campo---: {key} - Mensaje: {subError.ErrorMessage}");
                    }
                }
            }
            var usuarioActualId = Convert.ToInt32(User.Identity.Name);
            cita.UsuarioId = usuarioActualId;
            if (_citaService.AgendarCita(cita))
            {

                // return RedirectToAction("Confirmacion");
                // return RedirectToAction("index");

                TempData["MensajeExito"] = "¡Cita agendada con éxito!";

                return RedirectToAction("Index", "Cliente");
            }

            ModelState.AddModelError("", "El horario seleccionado ya no está disponible");
            ViewBag.Veterinarios = new SelectList(_usuarioService.ObtenerVeterinarios(), "Id", "NombreCompleto");
            return View();
        }
    }
}

vet360/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using vet360.Data;

namespace vet360.Controllers
{
    public class CuentaController : Controller
    {
        private Vet360Context db = new Vet360Context();

        [AllowAnonymous]
        public ActionResult Login() => View();

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(string correo, string contraseña)
        {
            var usuario = db.Usuarios
                .Include("Rol")
                .FirstOrDefault(u => u.Correo == correo && u.Contraseña == contraseña);

            if (usuario == null)
            {
                ViewBag.Mensaje = "Correo o contraseña incorrectos.";
                return View();
            }
            if (usuario.Rol == null)
            {
                ViewBag.Mensaje = "El usuario no tiene un rol asignado.";
                return View();
            }

            // Crear cookie de autenticación
            FormsAuthentication.SetAuthCookie(usuario.Id.ToString(), false);

            // Guardar rol en cookie personalizada (opcional)
            var authTicket = new FormsAuthenticationTicket(
                1,
                usuario.Id.ToString(),
                DateTime.Now,
                DateTime.Now.AddMinutes(30),
                false,
                usuario.Rol.Nombre
            );

            string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
            Response.Cookies.Add(cookie);

            // Redirigir según rol
            if (usuario.Rol.Nombre == "Veterinario")
                return RedirectToAction("Index", "Veterinario");
            else if (usuario.Rol.Nombre == "Cliente")
                return RedirectToAction("Index", "Cliente");

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        public ActionResult AccesoDenegado()
        {
            return View();
        }
    }
}

vet360/Controllers/MascotasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNetCore.Http;
using vet360.Data;
using vet360.Filters;
using vet360.Models;
using vet360.Services;
using vet360.Services.Impl;

namespace vet360.Controllers
{
    public class MascotasController : Controller
    {
        private readonly IMascotaService _mascotaService;
        private readonly IUsuarioService _usuarioService;

        public MascotasController()
        {
            _mascotaService = Global.ServiceProvider.GetService(typeof(IMascotaService)) as IMascotaService;
            _usuarioService = Global.ServiceProvider.GetService(typeof(IUsuarioService)) as IUsuarioService;
        }

        // GET: Mascotas
        [AutorizarRol("Veterinario", "Admin")]
        public ActionResult Index()
        {
            var mascotas = _mascotaService.ObtenerTodas();
            return View(mascotas);
        }

        // GET: Mascotas/MisMascotas
        [AutorizarRol("Cliente")]
        public ActionResult MisMascotas()
        {
            var ticket = (FormsIdentity)User.Identity;
            var username = ticket.Ticket.Name; // o Ticket.UserData si tenés el ID
            /*var rol = ticket.UserData;
            if (rol != "Veterinario")
            {
                return RedirectToAction("AccesoDenegado", "Error"); // o mostrar mensaje
            }*/
            var mascotasDelUsuario = _mascotaService.ObtenerPorUsuario(Convert.ToInt32(username));
            return View("Index", mascotasDelUsuario); // 
        }

        [HttpGet]
        public JsonResult ObtenerMisMascotasJson()
        {
            var ticket = (FormsIdentity)User.Identity;
            var username = ticket.Ticket.Name;
            var mascotasDelUsuario = _mascotaService.ObtenerPorUsuario(Convert.ToInt32(username));

            var resultado = mascotasDelUsuario.Select(m => new {
                id = m.Id,
                nombre = m.Nombre
            });

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        // GET: Mascotas/Details/5
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var mascota = _mascotaService.ObtenerPorId(id.Value);
            if (mascota == null)
                return HttpNotFound();

            return View(mascota);
        }

        // GET: Mascotas/Create
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        public ActionResult Create()
        {
           ViewBag.UsuarioId = new SelectList(_usuarioService.ListarTodos(), "Id", "Nombre");
            return View();
        }

        // POST: Mascotas/Create
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Especie,Raza,Edad,UsuarioId")] Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                _mascotaService.Crear(mascota);

                var user = HttpContext.User;

                var identity = (FormsIdentity)user.Identity;
                var rol = identity.Ticket.UserData;
                if(rol != "Cliente")
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("MisMascotas");

            }

            ViewBag.UsuarioId = new SelectList(_usuarioService.ListarTodos(), "Id", "Nombre");
            return View(mascota);
        }

        // GET: Mascotas/Edit/5
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var mascota = _mascotaService.ObtenerPorId(id.Value);
            System.Diagnostics.Debug.WriteLine("usuario controlador mascota: " + mascota.UsuarioId);
            if (mascota == null)
                return HttpNotFound();

            ViewBag.UsuarioId = new SelectList(_usuarioService.ListarTodos(), "Id", "Nombre", mascota.UsuarioId);
            return View(mascota);
        }

        // POST: Mascotas/Edit/5
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Especie,Raza,Edad,UsuarioId")] Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                System.Diagnostics.Debug.WriteLine("usuario procesado: " + mascota.UsuarioId);
                _mascotaService.Editar(mascota);
                var user = HttpContext.User;

                var identity = (FormsIdentity)user.Identity;
                var rol = identity.Ticket.UserData;
                if (rol != "Cliente")
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("MisMascotas");
            }

            ViewBag.UsuarioId = new SelectList(_usuarioService.ListarTodos(), "Id", "Nombre", mascota.UsuarioId);
            return View(mascota);
        }

        // GET: Mascotas/Delete/5
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var mascota = _mascotaService.ObtenerPorId(id.Value);
            if (mascota == null)
                return HttpNotFound();

            return View(mascota);
        }

        // POST: Mascotas/Delete/5
        [AutorizarRol("Cliente", "Veterinario", "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _mascotaService.Eliminar(id);

            var user = HttpContext.User;

            var identity = (FormsIdentity)user.Identity;
            var rol = identity.Ticket.UserData;
            if (rol != "Cliente")
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("MisMascotas");
        }
    }
}

vet360/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clínica Veterinaria</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        .navbar-custom {
            background-color: #5cb85c;
            border: none;
        }

            .navbar-custom .navbar-brand,
            .navbar-custom .navbar-nav > li > a {
                color: white !important;
                font-weight: bold;
            }

        .navbar-logo {
            height: 40px;
            margin-right: 10px;
        }

        footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ccc;
            text-align: center;
            color: #666;
        }

        .navbar-nav {
            display: flex;
            flex-direction: row;
            align-items: center;
            gap: 15px;
            margin: 0;
            justify-content: flex-end
        }

            .navbar-nav > li {
                list-style: none;
            }

        .navbar-text {
            color: white !important;
            font-weight: bold;
        }

        .navbar-nav > li > a {
            color: white !important;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="@Url.Action("Index", "Home")">
                <img src="~/Content/imagenes/logo.jpg" alt="Logo" class="navbar-logo" />
                Clínica Vet
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        var ticket = ((System.Web.Security.FormsIdentity)User.Identity).Ticket;
                        var rol = ticket.UserData;
                        var nombre = ticket.Name;

                        <li class="nav-item">
                            <span class="navbar-text me-3">
                                <i class="bi bi-person-circle"></i> Hola, @nombre
                            </span>
                        </li>

                        if (rol == "Cliente")
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("MisMascotas", "Mascotas")">Mis Mascotas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Agendar", "Cita")">Agendar Cita</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("MisCitas", "Cliente")">Mis Citas</a>
                            </li>
                        }
                        else if (rol == "Veterinario")
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Agenda", "Veterinario")">Agenda</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Pacientes", "Veterinario")">Pacientes</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Logout", "Cuenta")">Cerrar sesión</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Login", "Cuenta")">Iniciar sesión</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content" style="margin-top: 70px;">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Clínica Veterinaria</p>
        </footer>
    </div>

    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>-->

    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
    </html>